### ISSUE TITLE
Цель — минималистичность

### ISSUE THREAD

**Issue by Mazdaywik** [Mazdaywik/Refal-05#1]
Максимально упростить и язык, и компилятор.

* [x] Удалить интерпретируемый код. (#3)
* [x] Удалить идентификаторы. (#4)
* [x] Удалить статические ящики. (#5)
* [x] Удалить вложенные функции. (#6)
* [x] Удалить квадратные скобки. (#7)
* [x] Переписать на C89. (#8)
* [x] Переписать лексический анализ вручную, удалить lexgen. (#9)
* [x] Читать конфигурацию из переменных окружения (#19)
* [x] Удалить код переименования файлов (#20)
* [x] Почистить библиотеку встроенных функций (#21)
