### ISSUE TITLE
Синтаксис, совместимый с Рефалом-5

### ISSUE THREAD

**Issue by Mazdaywik** [Mazdaywik/Refal-05#2]
# Цель
Должна быть возможность писать программы, которые будут корректны и с точки зрения Рефала-05, и классического Рефала-5, т.е. у обоих языков должно быть общее подмножество. И это подмножество должно быть достаточно выразительно для того, чтобы на нём написать компилятор.

# Эскиз языка Рефал-05
Язык в первом приближении выглядит так:
* Синтаксис как у Рефала-5 или Простого Рефала — фигурные скобки, имена переменных через точку. Т.е. не как у Рефала-2.
* Базисный Рефал — предложения состоят только из образца и результата.
* Типы символов как в раннем Простом Рефале — литеры, числа и имена глобальных функций.
* Пустые функции задаются псевдокомментариями `*$ENUM`/`*$EENUM`, что обеспечит совместимость с Рефалом-5.
* Поддерживается подмножество встроенных функций Рефала-5, достаточное для самоприменения.
* Есть нативные вставки. Они идут в разрез с минималистичностью, но упрощают разработку библиотеки.

## Общее подмножество
* Имена enum’ов будем называть именами-идентификаторами. Имя-идентификатор должно либо создаваться и потребляться только в одной единице трансляции (и тогда объявлено как `*$ENUM`), или объявлено как `*$EENUM` и во всех остальных единицах объявлено как `$EXTERN`.
* Косвенный вызов функций осуществляется только через `Mu`.
* Для передачи функции для косвенного вызова из другой единицы трансляции её надо определить как entry. Поскольку функция `Mu` Рефала-5 умеет вызывать entry-функции из других единиц трансляции.

# Подзадачи
* [x] Разработка и уточнение синтаксиса языка. **(в комментариях)**
* [x] Реализация нового лексического анализатора. (#9)
* [x] Реализация нативных вставок. (#11)
* [x] Реализация библиотеки встроенных функций Рефала-5. (#12)

**Comment by Mazdaywik** [comment]
# Синтаксис Рефала-05
## Лексика
Лексика во многом повторяет лексику Простого Рефала версии 001. Типы токенов:

* Ключевые слова `$ENTRY`, `$EXTERN`, `$ENUM`, `$EENUM`.
* Целые числа — непустые последовательности десятичных цифр. Переполнение при компиляции не проверяется, их размер определяется разрядностью целевой платформы.
* Имена (функций) — последовательности букв, цифр, `_` и `-`, начинающиеся с буквы (прописной или строчной). Дефисы и прочерки считаются эквивалентными.
* Литеры — записываются в одинарных кавычках, поддерживают те же escape-последовательности, что и Рефал-5.
* Многострочные комментарии — как в Си `/* … */`.
* Однострочные комментарии — как в Рефале-5 — строка, первый символ которой `*`.
* Псевдокомментарии — строки, которые начинаются со звёздочки, после которой идёт допустимое ключевое слово. Текст после ключевого слова (возможно, отделённого пробельным символом) разбивается на лексемы обычным образом. В конце псевдокомментария неявно подразумевается точка с запятой.
* Переменные — `тип.имя`, где `тип` — одно из `s`, `t`, `e`, `имя` — непустая последовательность букв, цифр, `_` и `-`, причём `_` и `-` не различаются.
* Знаки пунктуации: `,`, `;`, `{`, `(`, `)`, `=`, `<`, `>`, `}`.
* Нативные вставки — оформляются точно также, как в Рефале-5λ

Псевдокомментарии предназначены для записи директив `$ENUM` и `$EENUM` невидимым для Рефала-5 способом. Если комментарий начинается с `*$`, но после `$` не располагается известного ключевого слова — он игнорируется.

Пример:
```
*$ENUM True, False
```
эквивалентно
```
$ENUM True, False;
```
(в конце неявная точка с запятой). В обоих случаях насчитываются следующие лексемы:

`$ENUM`, `True`, `,`, `False`, `;`

При этом
```
*$FROM LibraryEx
```
является обычным комментарием, поскольку `$FROM` не является допустимым ключевым словом.

Запись
```
*$ENTRY Hello { = World }
```
является допустимой конструкцией, однако, невидимой для Рефала-5. Это грязный хак.

## Грамматика
Здесь `|`, `ε` и `→` — метасимволы. В 〈угловых〉 скобках записаны типы токенов.
```
Program → ε | Program Element | Program;
Element → List; | Function | 〈native code〉
List → $ENUM 〈name〉 | $EENUM 〈name〉 | $EXTERN 〈name〉 | List, 〈name〉
Function → Scope 〈name〉 { Body }
Scope → $ENTRY | ε
Body → ε | Sentences; | Sentences | 〈native code〉
Sentences → Sentence | Sentences; Sentence
Sentence → Pattern = Result
Pattern → ε | Pattern PatternTerm
PatternTerm → Symbol | 〈variable〉 | (Pattern)
Result → ε | Result ResultTerm
ResultTerm → Symbol | 〈variable〉 | (Result) | <Result>
Symbol → 〈name〉 | 〈number〉 | 〈char〉
```

**Comment by Mazdaywik** [comment]
Сообщение коммита 05b53189abd5a79babae7fe6ebad531c2cf03cd2

> Компилятор собирается собой и при помощи refc/refgo (close #2)
>
> Старая стабильная версия (папка bootstrap) удалена, поскольку
> теперь компилятор раскручивается при помощи refc/refgo.
